Doc updates to correct file paths
Centiq/sap-hana pull request #61
Opened 2020-11-24 17:57 UTC by centiqmurphy

## Problem

When following the manual app installation process a few discrepancies were noticed in the documentation.

## Solution

This PR updates the application inifile generation inline with the current process.

## Tests

- [ ] Doc changes are correct

## Notes
<Additional comments for the PR>

2020-11-25 08:14 UTC, robfallows commented on documentation/ansible/system-design-deployment/app/prepare-ini.md
> +      SAPINST_INPUT_PARAMETERS_URL=/tmp/app_template/inifile.params         \
It would be good if `/tmp/app_template/inifile.params` could be `/tmp/app_template/MP_STACK_S4_2020_v001.inifile.params` to conform with the naming convention for files in `sapbits/templates`.

2020-11-25 08:35 UTC, robfallows approved these changes
LGTM 👍 but see comment in Slack.

2020-11-26 11:22 UTC, robfallows commented on documentation/ansible/system-design-deployment/app/prepare-ini.md
> +      SAPINST_INPUT_PARAMETERS_URL=/tmp/app_template/inifile.params         \
```suggestion
      SAPINST_INPUT_PARAMETERS_URL=/tmp/app_template/scs.inifile.params         \
```

2020-11-26 11:23 UTC, robfallows requested changes
Change requested

2020-11-26 16:10 UTC, peterchoo commented on documentation/ansible/system-design-deployment/app/prepare-bom.md
> +1. Using Microsoft Excel, open the download basket spreadsheet
This line looks incomplete.

2020-11-26 16:15 UTC, peterchoo commented on documentation/ansible/system-design-deployment/app/prepare-full-app-bom.md
> +1. :hand: The `SAPCAR` utility will need to be added separately, because even though it is in the SAP Download Basket, it will not be present in the spreadsheet. :information_source: The `version` pr
SWPM is also required as a manual addition AFAIK

2020-11-26 16:42 UTC, peterchoo commented on documentation/ansible/system-design-deployment/app/prepare-ini.md
> +      SAPINST_INPUT_PARAMETERS_URL=/tmp/app_template/scs.inifile.params         \
I just tried this, it wouldn't recognise any parameters for the file unless it was called `inifile.params`

2020-11-26 16:57 UTC, robfallows commented on documentation/ansible/system-design-deployment/app/prepare-ini.md
> +      SAPINST_INPUT_PARAMETERS_URL=/tmp/app_template/scs.inifile.params         \
With or without the path?

2020-12-02 14:47 UTC, robfallows commented on documentation/ansible/system-design-deployment/app/prepare-full-app-bom.md
> +1. :hand: The `SAPCAR` utility will need to be added separately, because even though it is in the SAP Download Basket, it will not be present in the spreadsheet. :information_source: The `version` pr
It's definitely in the example boms without doing anything special.

2020-12-02 14:56 UTC, robfallows commented on documentation/ansible/system-design-deployment/app/prepare-bom.md
> +1. Using Microsoft Excel, open the download basket spreadsheet
It needed moving down!

2020-12-02 15:10 UTC, robfallows commented on documentation/ansible/system-design-deployment/app/prepare-system.md
> +1. Configure recommened swapfile size (e.g. sizings outlined in [SAP note 1597355](https://launchpad.support.sap.com/#/notes/1597355)
```suggestion
1. Configure recommended swapfile size (e.g. sizings outlined in [SAP note 1597355](https://launchpad.support.sap.com/#/notes/1597355)
```

2020-12-02 15:11 UTC, robfallows commented on documentation/ansible/system-design-deployment/hana/prepare-system.md
> +1. Configure recommened swapfile size (e.g. sizings outlined in [SAP note 1597355](https://launchpad.support.sap.com/#/notes/1597355)
```suggestion
1. Configure recommended swapfile size (e.g. sizings outlined in [SAP note 1597355](https://launchpad.support.sap.com/#/notes/1597355)
```

2020-12-02 15:11 UTC, robfallows approved these changes
Two small typos to fix, otherwise LGTM 👍

2020-12-02 15:18 UTC, merged